### ISSUE TITLE
Couch in Graz/Austria

### ISSUE THREAD

**Issue by mane87** [ashfurrow/EuroTrip-2015#4]
Hey ash, we have met at last years uikonf :). i would love to offer you a couch for a few days! Graz is located two hours in the south from Vienna...

Have a look at it in Apple maps!

**Comment by ashfurrow** [comment]
Oh wow, thanks! I'm coordinating a few other plans, so I'll get back to you ASAP. Thanks again!

**Comment by AshleyKrista** [comment]
Cool :)

it’s south of prague, the same distance it is from berlin to prague… 9 hours from berlin.

But we could do it and see prague right on the way, so  :P

-- 
Ashley Furrow
Sent with Airmail

On April 13, 2015 at 4:41:32 PM, Ash Furrow (notifications@github.com) wrote:

Oh wow, thanks! I'm coordinating a few other plans, so I'll get back to you ASAP. Thanks again!

**Comment by mane87** [comment]
There are some really cheap train tickets available from Prag to Graz from time to time.

**Comment by ashfurrow** [comment]
Hey @mane87 – we've got our itinerary filled up, and it doesn't look like we'll be able to visit you on this trip. Next time!
